version: "2"         # required to adjust maintainability checks
checks:
  file-lines:
    config:
      threshold: 1000
plugins:
  bandit:
    enabled: true
  fixme:
    enabled: true
  git-legal:
    enabled: true
  radon:
    enabled: true
  sonar-python:
    enabled: true
    config:
      tests_patterns:
        - selftests/**
