---
name: Run-perf CI

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  selftests:
    name: ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          fetch-tags: true
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install missing aexpect dependency (remove when https://github.com/avocado-framework/aexpect/pull/81 is merged)
        run: pip install six numpy
      - run: pip install -e .[dev]
      - run: make check
